#!/bin/bash

screen_size=$(xrandr | awk '/connected primary/{print $4}')

set_applications_rules() {
    applications=$1

    # Default desktop
    desktop='desktop=^1'

    for data in "${applications[@]}"; do
        # Split applications data
        IFS='|' read -r -a data <<< "$data"

        app=${data[@]:0:1}
        app_rules=${data[@]:1}

        if [[ $app == ^* ]]; then
            desktop="desktop=${app}"
            continue

        elif [[ $data == --* ]]; then
            desktop=''
            continue

        fi

        # Call bspc
        bspc rule -a "$app" $desktop follow=true $app_rules
    done
}

declare -a applications=(
    '^2'
    'Code'

    '^3'
    'Chromium'
    'firefox'
	'Falkon'

    '^4'
    'Gtk3-youtube-viewer'
    'Thunar'

    '^5'
    'Atril'
	'feh'
    'Master PDF Editor'
    'mpv'
    'qpdfview'
    'vlc'
    'Wps'
    'Wpspdf'

    '^6'
    'TelegramDesktop'

    '^7'
    'Kodi'
    'Thunderbird'

    '^8'
    'Subl3'

    '^9'
    'TeamViewer'

    '--'
    'com-rarchives-ripme-App    | state=floating'
    'MEGAsync                   | state=floating'
    "st-popup                   | layer=above state=floating hidden=true sticky=true border=false rectangle=${screen_size}"
    'Uget-gtk                   | state=floating'
    'xdman-Main                 | state=floating follow=false'
)

set_applications_rules $applications
