#!/bin/bash

wmname LG3D &
xdman -m >/dev/null &

# {
#     # Kill script by script path
#     #
#     kill `ps -aux | grep SCRIPT | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
# } &

{
    killall -q -w sxhkd
    sxhkd
} &

{
    killall -q -w polybar
    polybar top
} &

{
    killall -q -w xfce-polkit
    /usr/lib/xfce-polkit/xfce-polkit
} &

{
    killall -q -w xfce4-notifyd dunst
    dunst
} &

[[ ! $(xdo id -N st-popup) ]] && {
    ~/.scripts/st-popup.sh
} &

[[ ! $(xdo id -N st-256color -n st-256color) ]] && {
    bspc rule -a 'st-256color:st-256color' --one-shot desktop='^1' follow=false
    st
} &
