#!/bin/dash

# Killall running proccess
pkill -USR1 -x sxhkd

# Variables
screen_size=$(xrandr | awk '/connected primary/{print $4}')

# Autolaunch
sxhkd &
play-with-mpv &
nitrogen --restore &
/opt/xdman/jre/bin/java -Xmx1024m -jar /opt/xdman/xdman.jar -m &

$HOME/.config/mpd/launch.sh &
$HOME/.config/dunst/launch.sh &
$HOME/.config/polybar/launch.sh &
$HOME/.config/compton/launch.sh &

# Config
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width                2
bspc config window_gap                  4
# bspc config top_padding               0
bspc config bottom_padding              32

bspc config split_ratio                 0
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config focus_follows_pointer       true

# mod1 - alt (left)
# mod4 - super
bspc config pointer_modifier            mod4

bspc config focused_border_color        "#353535"
bspc config active_border_color         "#191919"
bspc config normal_border_color         "#191919"
bspc config presel_feedback_color       "#151515"

# Rules
bspc rule -a 'Codium' desktop='^2' follow=on
bspc rule -a 'Sublime_text' desktop='^2' follow=on
bspc rule -a 'Emacs' desktop='^2' follow=on state=tiled
bspc rule -a 'tabbed:surf' desktop='^3' follow=on
bspc rule -a 'Chromium-browser' desktop='^3' follow=on
bspc rule -a 'Firefox' desktop='^3' follow=on
bspc rule -a 'Thunar' desktop='^4' follow=on
bspc rule -a 'Kodi' desktop='^5' follow=on
bspc rule -a 'vlc' desktop='^5' follow=on
bspc rule -a 'mpv' desktop='^5' follow=on
bspc rule -a 'Atril' desktop='^5' follow=on
bspc rule -a 'TeamViewer' desktop='^9' follow=on

bspc rule -a 'com-rarchives-ripme-App' follow=on state=floating
bspc rule -a 'tabbed:urxvt-popup' follow=on state=floating hidden=on sticky=on rectangle=$screen_size
bspc rule -a 'tabbed:urxvt-scrot' hidden=off

# Etc
# kill `ps -aux | grep SCRIPT | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1

[ -z "$(pidof urxvtd)" ] && {
    urxvtd -q &

    while ! pgrep -x urxvtd > /dev/null; do
        sleep 1
    done
}

[ -z "$(xdo id -N URxvt -n urxvt)" ] && {
    urxvtc &
}

[ -z "$(xdo id -N tabbed -n urxvt-popup)" ] && {
    tabbed -n urxvt-popup -f -r 2 urxvtc -embed '' -e tmux new-session \; split-window -v \; resize-pane -D 30 \; \
        select-pane -t 0 \; split-window -h \; select-pane -t 0 \; attach > /dev/null 2>&1 &
}
