#!/bin/bash

sxhkd &
$HOME/.config/mpd/launch.sh &
$HOME/.config/polybar/launch.sh &
$HOME/.config/compton/launch.sh &
/opt/xdman/jre/bin/java -Xmx1024m -jar "/opt/xdman/xdman.jar" -m &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width                2
bspc config window_gap                  4

bspc config split_ratio                 0
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config focus_follows_pointer       true

bspc config focused_border_color        "#353535"
bspc config active_border_color         "#191919"
bspc config normal_border_color         "#191919"
bspc config presel_border_color         "#a2a2a2"

bspc config bottom_padding              32

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a 'Codium' desktop='2' follow=on
bspc rule -a 'Sublime_text' desktop='2' follow=on
bspc rule -a 'Emacs' desktop='2' follow=on state=tiled
bspc rule -a 'Chromium-browser' desktop='3' follow=on
bspc rule -a 'Firefox' desktop='3' follow=on
bspc rule -a 'Pcmanfm' desktop='4' follow=on
bspc rule -a 'Thunar' desktop='4' follow=on
bspc rule -a 'Kodi' desktop='5' follow=on
bspc rule -a 'vlc' desktop='5' follow=on
bspc rule -a 'mpv' desktop='5' follow=on
bspc rule -a 'Atril' desktop='5' follow=on
bspc rule -a 'TeamViewer' desktop='9' follow=on

bspc rule -a 'com-rarchives-ripme-App' follow=on state=floating

[[ ! $(pidof urxvt) ]] && {
    bspc rule -a 'URxvt' desktop='^1'
    urxvt &
    sleep 2
    bspc rule -r 'URxvt'
}

[[ ! $(bspc query -N -n .hidden) ]] && {
    bspc rule -a 'URxvt' state=floating hidden=on sticky=on rectangle=$(xrandr | awk '/connected primary/{print $4}')
    urxvt -e tmux new-session \; split-window -h \; split-window -v \; select-pane -t 1 \; select-pane -t 0 \; attach &
    sleep 1
    bspc rule -r 'URxvt'
}
