#!/bin/sh

xdman -m >/dev/null &

# {
#     killall -q -w picom
#     picom
# } &

{
    killall -q -w xfce-polkit
    /usr/lib/xfce-polkit/xfce-polkit
} &

{
	killall -q -w trayer
	trayer --edge top --align center --widthtype request --height 22 --transparent true --alpha 0 --tint 0xff101216
} &

{
	killall -q -w play-with-mpv
	play-with-mpv
} &
