#!/bin/sh

set_screen() {
	mode=$(cvt $1 $2 | awk -F 'Modeline ' '/Modeline/ { print $2 }' | sed 's/"//g')
	resolution=$(echo $mode | cut -d " " -f 1)

	xrandr --newmode $mode
	xrandr --addmode VGA-0 $resolution
	xrandr --output VGA-0 --mode $resolution
}

# set_screen 1364 768
