#!/bin/bash

mkdir -p "${HOME}/Downloads/Stream"

datetime="$(date '+%F-%H-%M-%S')"

while IFS='|' read -ra arg; do
    for i in "${arg[@]}"; do
        url="$i"
        break
    done
done <<< "$1"

if [[ $url = http* ]]; then
    notify-send -t 5000 'Mpv Stream Opened' "$url"

    mpv "$url" --stream-record="${HOME}/Downloads/Stream/${datetime}.ts" --keep-open=no --fullscreen=yes \
        --script-opts=osc-visibility=always

    notify-send -t 3000 'Mpv Stream Closed'
else
    mpv $* --keep-open=no --fullscreen=yes
fi
