#!/bin/bash

mkdir -p "${HOME}/Downloads/Stream"

datetime="$(date '+%Y-%m-%d-%H-%M-%S')"

while IFS='|' read -ra arg; do
    for i in "${arg[@]}"; do
        url="$i"
        break
    done
done <<< "$1"

if [[ $url == http* ]]; then
    mpv "$url" --stream-record="${HOME}/Downloads/Stream/${datetime}.ts" --keep-open=no --fullscreen=yes \
        --script-opts=osc-visibility=always
else
    mpv $* --keep-open=no --fullscreen=yes
fi
