# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # # Simple text replacement
  # - trigger: ":espanso"
  #   replace: "Hi there!"

  # # Dates
  # - trigger: ":date"
  #   replace: "{{mydate}}"
  #   vars:
  #     - name: mydate
  #       type: date
  #       params:
  #         format: "%m/%d/%Y"

  # # Shell commands
  # - trigger: ":shell"
  #   replace: "{{output}}"
  #   vars:
  #     - name: output
  #       type: shell
  #       params:
  #         cmd: "echo Hello from your shell"

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo -n $(dig @resolver1.opendns.com myip.opendns.com +short)"

  - trigger: ":gw"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo -n $(ip route | grep default | awk '{ print $3 }' | tail -n 1)"
